"""empty message

Revision ID: 69b79771bbb6
Revises: 01308d5d4efe
Create Date: 2025-06-09 17:11:41.188108

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "69b79771bbb6"
down_revision: Union[str, None] = "01308d5d4efe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_otp", sa.Boolean(), nullable=False))
    op.drop_column("user", "is_otp_enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_otp_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("user", "is_otp")
    # ### end Alembic commands ###
