"""User model password field name change

Revision ID: adc184b20fbe
Revises: cb2765c60858
Create Date: 2025-05-15 16:29:03.652364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "adc184b20fbe"
down_revision: Union[str, None] = "cb2765c60858"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.drop_column("user", "hashes_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("hashes_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
