"""empty message

Revision ID: d8959c0a7403
Revises: dd0e4c6bf1cd
Create Date: 2025-06-09 15:40:06.462431

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d8959c0a7403"
down_revision: Union[str, None] = "dd0e4c6bf1cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credentials", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.add_column("user", sa.Column("last_login", sa.DateTime(), nullable=True))
    op.alter_column(
        "user", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_column("user", "last_login")
    op.alter_column(
        "credentials",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###
